QLNH/ViewComponents/MenuTopViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using QLNH.Models;

namespace QLNH.ViewComponents
{
    public class MenuTopViewComponent : ViewComponent
    {
        private readonly DoAnPtudwContext _context;

        public MenuTopViewComponent(DoAnPtudwContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = _context.TblMenus.Where(m => (bool)m.IsActive).
                OrderBy(m => m.Position).ToList();
            return await Task.FromResult<IViewComponentResult>(View(items));
        }
    }
}

QLNH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Italian Cuisine</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="~/img/favicon.ico" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,500,600|Pacifico" rel="stylesheet">

    <!-- Bootstrap CSS File -->
    <link href="~/vendor//bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Libraries CSS Files -->
    <link href="~/vendor//font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/vendor//animate/animate.min.css" rel="stylesheet">
    <link href="~/vendor//owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/vendor//tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Main Stylesheet File -->
    <link href="~/css/style.css" rel="stylesheet">
</head>

<body>

    <!-- Top Header Start -->
    <section id="top-header">
        <div class="logo">
            <img src="img/logo.png" />
        </div>
    </section>
    <!-- Top Header End -->
    <!-- Header Start -->
    <header id="header">
        <div class="container">
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    @await Component.InvokeAsync("MenuTop")
                </ul>
            </nav>
        </div>
    </header>
    <!-- Header End -->

    @RenderBody()

    <!-- Footer Start -->
    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="copyright">
                        <p>&copy; Copyright <a href="">Your Site Name</a>. All Rights Reserved</p>

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        <p>Designed By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
                <div class="col-sm-6">
                    <ul class="icon">
                        <li><a href="#" class="fa fa-twitter"></a></li>
                        <li><a href="#" class="fa fa-facebook"></a></li>
                        <li><a href="#" class="fa fa-pinterest"></a></li>
                        <li><a href="#" class="fa fa-google-plus"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer end -->

    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="~/vendor//jquery/jquery.min.js"></script>
    <script src="~/vendor//jquery/jquery-migrate.min.js"></script>
    <script src="~/vendor//bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor//easing/easing.min.js"></script>
    <script src="~/vendor//stickyjs/sticky.js"></script>
    <script src="~/vendor//superfish/hoverIntent.js"></script>
    <script src="~/vendor//superfish/superfish.min.js"></script>
    <script src="~/vendor//owlcarousel/owl.carousel.min.js"></script>
    <script src="~/vendor//tempusdominus/js/moment.min.js"></script>
    <script src="~/vendor//tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/vendor//tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Main Javascript File -->
    <script src="~/js/main.js"></script>

</body>
</html>